---
- name: update /etc/nginx/sites-available/jenkins from template
  template:
    src: etc/nginx/sites-available/jenkins
    dest: /etc/nginx/sites-available/jenkins
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: ensure /etc/nginx/sites-enabled/jenkins exists and links to ../sites-available/jenkins
  file:
    path: /etc/nginx/sites-enabled/jenkins
    src: ../sites-available/jenkins
    force: yes
    state: link
  notify:
    - restart nginx

- name: ensure that there is not a hostname collision with the nginx default host
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: '^(\s+)(server_name {{ jenkins_hostname }};.*)$'
    backrefs: yes
    line: '\1#\2'
    state: present
  notify:
    - restart nginx

- name: ensure jenkins services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - jenkins
    - nginx

