---
- name: ensure jenkins is started and enabled
  service:
    name: jenkins
    state: started
    enabled: yes

#- name: restart mariadb if necessary
#  service:
#    name: mysql
#    state: restarted
#  when: my_cnf|changed
