---
- name: ensure jenkins dependency packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - python-software-properties

- name: ensure jenkins repository public key is installed
  apt_key: 
    url: "{{ jenkins_apt_key_url }}"
    state: present

- name: ensure jenkins repository is enabled
  apt_repository: 
    repo: "{{ jenkins_apt_repository }}"
    update_cache: yes
    state: present

- name: ensure jenkins packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - jenkins
