---
- include: prep.yml

- include: docker.yml
  when: jenkins_dockerized_deployment

- include: install.yml
  when: not jenkins_dockerized_deployment

- include: configure.yml
  when: not jenkins_dockerized_deployment 
