---
- include: docker.yml
  when: mariadb_dockerized_deployment

- include: install.yml
  when: not mariadb_dockerized_deployment

- include: offline_configuration.yml
  when: not mariadb_dockerized_deployment 

- include: online_configuration.yml
  when: not mariadb_dockerized_deployment
