---
- name: update mariadb root password for local root account
  mysql_user: 
    name: root 
    host: localhost 
    password: "{{ mariadb_mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update .my.cnf file with root password credentials
  template: 
    src: root/.my.cnf 
    dest: /root/.my.cnf 
    owner: root 
    group: root 
    mode: 0600

- name: update mariadb root password for docker host
  mysql_user: 
    name: root 
    host: "{{ ansible_docker0['ipv4']['address'] }}"
    password: "{{ mariadb_mysql_root_password }}" 
    priv: "*.*:ALL,GRANT"
    state: present
  when: mariadb_docker_context is defined
