---
- name: restart mariadb
  service: 
    name: mysql
    state: restarted
  when: mariadb_dockerize_context is not defined

- name: perform mariadb online configuration
  docker:
    image: "{{ mariadb_docker_username }}/mariadb"
    volumes_from: mariadb_data
    detach: no
    command: >
              ansible-playbook -i inventories/local.ini deploy.yml -e '{
                "mariadb_dockerize_context" : "online_configuration",
                "mariadb_mysql_root_password" : 
                  "{{ mariadb_mysql_root_password }}" }'
    state: restarted
