---
- name: restart mariadb
  service: 
    name: mysql
    state: restarted

# FIXME: this could be done with a script, but would that be more secure?
- name: set mariadb root password for docker host
  docker:
    image: "{{ mariadb_docker_username }}/mariadb"
    volumes_from: mariadb_data
    detach: no
    command: >
              cd /var/cache/docker/mariadb &&
              ansible-playbook -i inventories/local.ini deploy.yml
                -e mariadb_dockerize_context=online_configuration
    state: restarted
